### ISSUE TITLE
Improper line placement on plot with set_ticks

### ISSUE THREAD

**Issue by Atulsingh92** [kravitsjacob/paxplot#27]
Hi, 
The column with $N_{plates}$ is essentially 0, however the comparison I am making this plot with, has $N_{plates}$ as [0,1,2,3]. 
Hence I also want [0,1,2,3] in this plot for $N_{plates}$
![image](https://github.com/kravitsjacob/paxplot/assets/30570817/4d84a922-f78e-4fe6-845c-a587da98007c)

I've achieved the above with 

```
paxfig.set_ticks(ax_idx = 6,
                  ticks  = [0, 1, 2],
                  labels = ['0', '1', '2'])
```

Could anyone please suggest a way such that zero is at the bottom of the line drawn? and I can get 4 ticks of [0,1,2,3]??

**Comment by Atulsingh92** [comment]
Solved it with, 
```
paxfig.set_ticks(ax_idx = 6,
                  ticks  = [0, 1, 2, 3],
                  labels = ['0', '1', '2', '3'])
paxfig.set_lim(ax_idx=6, bottom=0, top=3)
```

**Comment by kravitsjacob** [comment]
I was going to get to this in a few days, you beat me to it, good job!

The fact it didn't do this by default may be a bug... will investigate later!
