### ISSUE TITLE
Draw a grouped parallel coordinate plot with 2 sets of data

### ISSUE THREAD

**Issue by Huihui-Mao** [kravitsjacob/paxplot#29]
Hi, 
I want to draw a grouped parallel coordinate plot with 2 sets of data in a graph, with each of the 2 sets of data represented in a different colour (using a single colour for each category, not a colorbar), and display the legend, and also, put the legend directly below the figure, not on the right side. Is there any way to achieve this?
![Snipaste_2024-04-07_15-47-54](https://github.com/kravitsjacob/paxplot/assets/42145787/95136a50-a032-48ca-8aac-7a0bab78d83d)

**Comment by kravitsjacob** [comment]
Hey @Huihui-Mao! My apologies for the late reply - this is now a project I work on in my free time, which is limited these days! Someday I will get to cleaning the codebase up...

Yes, what you have requested is possible. Here is my totally hacky way of doing it.

```
import paxplot
import matplotlib.pyplot as plt

# Generate data
subset_a_data = [
    [0.0, 0.0, 2.0, 0.5],
    [0.5, 0.5, 0.5, 0.75],
    [3.0, 2.0, 0.0, 0.9],
]
subset_b_data = [
    [1.0, 1.0, 1.0, 1.0],
    [2.5, 1.5, 1.5, 1.0],
]

# Make the paxfig plot
paxfig = paxplot.pax_parallel(n_axes=4)
paxfig.plot(
    subset_a_data, # Plot the a subset
    line_kwargs={'color': 'blue'}
)
paxfig.plot(
    subset_b_data, # Plot the b subset
    line_kwargs={'alpha': 0.5, 'color': 'grey', 'zorder': 0}
)

# Add custom legend for A subset 
chosen_line = paxfig.axes[0].lines[-3] # Make sure you choose a line from subset A
paxfig.axes[1].legend(
    [chosen_line],
    ['Subset A'],
    loc='center'
)
paxfig.axes[1].get_legend().set_bbox_to_anchor((0.0, -0.1))

# Add custom legend for B subset
chosen_line = paxfig.axes[0].lines[-1] # Make sure you choose a line from subset B
paxfig.axes[2].legend(
    [chosen_line],
    ['Subset B'],
    loc='center'
)
paxfig.axes[2].get_legend().set_bbox_to_anchor((0.0, -0.1))

paxfig.savefig("reply.png")
plt.show()
```

Here is the result `reply.png`

![reply](https://github.com/kravitsjacob/paxplot/assets/49840473/bdb70a55-0d17-475f-aa03-908b67c269da)

**Comment by Huihui-Mao** [comment]
Thank you very much for your reply!
